# Generated by Django 5.1.1 on 2024-09-26 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('nacionalidad', models.CharField(max_length=100)),
                ('productora', models.CharField(max_length=100)),
                ('fecha', models.DateTimeField()),
            ],
        ),
    ]
