# Generated by Django 5.1.1 on 2024-10-16 01:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Actores',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, db_column='Nombre', max_length=255, null=True)),
                ('nacionalidad', models.CharField(blank=True, db_column='Nacionalidad', max_length=255, null=True)),
                ('sexo', models.CharField(blank=True, db_column='Sexo', max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, db_column='Nombre', max_length=255, null=True)),
                ('nacionalidad', models.CharField(blank=True, db_column='Nacionalidad', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('imagen', models.ImageField(null=True, upload_to='img/')),
                ('titulo', models.CharField(db_column='Titulo', max_length=255, null=True)),
                ('nacionalidad', models.CharField(db_column='Nacionalidad', max_length=255, null=True)),
                ('productor', models.CharField(db_column='Productor', max_length=255, null=True)),
                ('fecha', models.DateField(db_column='Fecha', max_length=255, null=True)),
                ('id_director', models.ForeignKey(db_column='ID_Director', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='movies.director')),
            ],
        ),
        migrations.CreateModel(
            name='Ejemplar',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('estado_conservacion', models.CharField(blank=True, db_column='Estado_conservacion', max_length=255, null=True)),
                ('id_pelicula', models.ForeignKey(blank=True, db_column='Id_Pelicula', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='movies.pelicula')),
            ],
        ),
        migrations.CreateModel(
            name='Reparto',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('id_actores', models.ForeignKey(db_column='Id_Actores', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='movies.actores')),
                ('id_pelicula', models.ForeignKey(db_column='Id_Pelicula', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='movies.pelicula')),
            ],
        ),
        migrations.CreateModel(
            name='Socio',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('dni', models.CharField(db_column='DNI', max_length=255, null=True)),
                ('nombre', models.CharField(db_column='Nombre', max_length=255, null=True)),
                ('direccion', models.CharField(db_column='Direccion', max_length=255, null=True)),
                ('telefono', models.CharField(db_column='Telefono', max_length=255, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='socio', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Codeudor',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('id_codeudor', models.ForeignKey(blank=True, db_column='Id_Codeudor', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='codeudor_id_codeudor_set', to='movies.socio')),
                ('id_socio', models.ForeignKey(blank=True, db_column='Id_socio', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='movies.socio')),
            ],
        ),
        migrations.CreateModel(
            name='Alquiler',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('fecha_alquiler', models.CharField(blank=True, db_column='Fecha_Alquiler', max_length=255, null=True)),
                ('fecha_devolucion', models.CharField(blank=True, db_column='Fecha_Devolucion', max_length=255, null=True)),
                ('as_delivered', models.IntegerField(blank=True, null=True)),
                ('id_ejemplar', models.ForeignKey(blank=True, db_column='Id_ejemplar', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='movies.ejemplar')),
                ('id_socio', models.ForeignKey(blank=True, db_column='Id_socio', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='movies.socio')),
            ],
        ),
    ]
