# Generated by Django 5.1.1 on 2024-10-05 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_pelicula_fecha'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pelicula',
        ),
    ]
