# Generated by Django 5.1.1 on 2024-10-06 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pelicula',
            options={},
        ),
    ]
