# Generated by Django 5.1.1 on 2024-10-06 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_pelicula_id_director_pelicula_imagen_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pelicula',
            name='id_director',
        ),
    ]
