# Generated by Django 5.1.1 on 2024-10-06 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_remove_pelicula_id_director'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pelicula',
            options={'managed': False},
        ),
    ]
