# Generated by Django 5.1.1 on 2024-10-14 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_alter_pelicula_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='socio',
            options={},
        ),
    ]
