# Generated by Django 5.1.1 on 2024-10-16 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_socio_user_alter_socio_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actores',
            options={},
        ),
        migrations.AlterModelOptions(
            name='alquiler',
            options={},
        ),
        migrations.AlterModelOptions(
            name='codeudor',
            options={},
        ),
        migrations.AlterModelOptions(
            name='director',
            options={},
        ),
        migrations.AlterModelOptions(
            name='ejemplar',
            options={},
        ),
        migrations.AlterModelOptions(
            name='pelicula',
            options={},
        ),
        migrations.AlterModelOptions(
            name='reparto',
            options={},
        ),
        migrations.AlterField(
            model_name='socio',
            name='dni',
            field=models.CharField(db_column='DNI', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='socio',
            name='telefono',
            field=models.CharField(db_column='Telefono', max_length=255, null=True),
        ),
    ]
